runtime:
  # 资源限制
  max_memory_usage: 1024  # MB
  max_cpu_usage: 80.0     # 百分比
  max_disk_usage: 10240   # MB
  
  # 缓存配置
  cache_enabled: true
  cache_size: 100         # MB
  cache_ttl: 3600         # 秒
  cache_cleanup_interval: 1800  # 秒
  
  # 日志配置
  log_level: "INFO"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_file: "logs/app.log"
  log_max_size: 10485760  # 10MB
  log_backup_count: 5
  log_rotation: "time"    # time 或 size
  log_rotation_when: "midnight"
  log_rotation_interval: 1
  
  # 监控配置
  metrics_enabled: true
  metrics_port: 9090
  metrics_path: "/metrics"
  tracing_enabled: false
  tracing_endpoint: null
  
  # 性能监控
  performance_monitoring:
    enabled: true
    sample_rate: 0.1
    slow_query_threshold: 1000  # ms
    memory_check_interval: 60   # 秒
    cpu_check_interval: 30      # 秒
    disk_check_interval: 300    # 秒
  
  # 临时文件管理
  temp_dir: "/tmp/chatexcel"
  temp_cleanup_interval: 3600  # 秒
  temp_max_age: 86400         # 秒
  temp_max_size: 1073741824   # 1GB
  
  # 并发控制
  concurrency:
    max_workers: 4
    max_concurrent_requests: 100
    request_timeout: 30
    worker_timeout: 60
    queue_size: 1000
  
  # 健康检查
  health_check:
    enabled: true
    endpoint: "/health"
    interval: 30
    timeout: 5
    checks:
      - name: "memory"
        type: "resource"
        threshold: 90
      - name: "cpu"
        type: "resource"
        threshold: 95
      - name: "disk"
        type: "resource"
        threshold: 85
      - name: "database"
        type: "service"
        enabled: false
      - name: "external_api"
        type: "service"
        enabled: false
  
  # 错误处理
  error_handling:
    max_retries: 3
    retry_delay: 1000      # ms
    exponential_backoff: true
    circuit_breaker_enabled: true
    circuit_breaker_threshold: 5
    circuit_breaker_timeout: 60  # 秒
  
  # 数据处理
  data_processing:
    max_rows_per_file: 1000000
    max_columns_per_file: 1000
    chunk_size: 10000
    parallel_processing: true
    memory_efficient_mode: true
  
  # 网络配置
  network:
    connection_pool_size: 10
    connection_timeout: 30
    read_timeout: 60
    max_redirects: 3
    verify_ssl: true
  
  # 调试配置
  debug:
    enabled: false
    profiling_enabled: false
    trace_requests: false
    dump_config_on_start: false
    verbose_errors: false
  
  # 特性开关
  features:
    excel_charts: true
    data_validation: true
    file_compression: true
    async_processing: true
    batch_operations: true
    export_formats: ["xlsx", "csv", "json", "html"]
  
  # 国际化
  i18n:
    default_locale: "zh_CN"
    supported_locales: ["zh_CN", "en_US"]
    timezone: "Asia/Shanghai"
  
  # 通知配置
  notifications:
    enabled: false
    email_enabled: false
    webhook_enabled: false
    slack_enabled: false
    
  # 备份配置
  backup:
    enabled: true
    interval: 86400        # 24小时
    retention_days: 30
    compress: true
    location: "./backups"
    
  # 清理配置
  cleanup:
    enabled: true
    interval: 3600         # 1小时
    max_age_days: 7
    clean_temp_files: true
    clean_log_files: true
    clean_cache_files: true